name: Generate and Import ToC into README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate ToC for all Markdown files
        run: |
          echo "## Table of Contents" > TOC.md
          echo "" >> TOC.md
          find . -type f -name "*.md" | while read file; do
            echo "- [$file]($file)" >> TOC.md
          done

      - name: Remove old ToC from README.md
        run: |
          # Remove any existing ToC from README.md (assumes it's inside a comment or special section)
          sed -i '/## Table of Contents/,/^$/d' README.md

      - name: Import new TOC into README.md
        run: |
          # Read the content of TOC.md and README.md
          TOC_CONTENT=$(cat TOC.md)
          README_CONTENT=$(cat README.md)

          # Insert the TOC content above the first heading (or at the top)
          if grep -q "^#" <<< "$README_CONTENT"; then
            # Use printf to insert the TOC at the beginning or before the first heading
            NEW_README=$(echo "$README_CONTENT" | sed "0,/^#/s/^#/## Table of Contents\n\n$TOC_CONTENT\n\n#/")
          else
            # If no heading is found, insert TOC at the top of the file
            NEW_README="$TOC_CONTENT\n\n$README_CONTENT"
          fi

          # Write the updated README.md back
          echo "$NEW_README" > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Import and update Table of Contents"
          git push origin HEAD:main
