name: Generate and Import ToC into README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate ToC for all Markdown files
        run: |
          # Generate TOC.md with links to all markdown files
          echo "" > TOC.md
          find . -type f -name "*.md" | while read file; do
            echo "- [$file]($file)" >> TOC.md
          done

      - name: Remove old ToC from README.md
        run: |
          # Remove any existing Table of Contents from README.md
          sed -i '/## Table of Contents/,/^$/d' README.md

      - name: Import new TOC into README.md
        run: |
          TOC_CONTENT=$(cat TOC.md)

          # Insert TOC_CONTENT after the '## Table of Contents' section in README.md
          awk -v TOC="$TOC_CONTENT" '
            /## Table of Contents/ { 
              print $0 "\n" TOC; 
              next 
            }
            { print }
          ' README.md > README.md.temp && mv README.md.temp README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Import and update Table of Contents"
          git push origin HEAD:main
