name: Generate and Import ToC into README
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate and update ToC
        run: |
          # Generate TOC.md with links to all markdown files
          find . -type f -name "*.md" | sort | while read file; do
              echo "- [$file]($file)"
          done > TOC.md

          # Remove old ToC and insert new one in README.md
          awk '
              BEGIN { 
                  in_toc = 0 
                  toc = ""
              }
              # Read TOC.md content into variable
              BEGINFILE { 
                  if (FILENAME == "TOC.md") {
                      while ((getline line < "TOC.md") > 0) {
                          toc = toc line "\n"
                      }
                      nextfile
                  }
              }
              # Process README.md
              /^[#]{2} Table of Contents/ {
                  print
                  print toc
                  print ""
                  in_toc = 1
                  next
              }
              in_toc && /^[#]/ {
                  in_toc = 0
              }
              !in_toc {
                  print
              }
          ' TOC.md README.md > tmp && mv tmp README.md
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update Table of Contents"
          git push origin HEAD:main
