name: Generate Table of Contents for Files

on:
  push:
    branches:
      - main
jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate ToC for files
        run: |
          echo "## Table of Contents" > TOC.md
          echo "" >> TOC.md
          find . -type f -name "*.md" | while read file; do
            echo "- [$file]($file)" >> TOC.md
          done

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add TOC.md
          git commit -m "Update Table of Contents"
          git push
